---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: fastapi-llm-app
  name: fastapi-llm-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fastapi-llm-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fastapi-llm-app
    spec:
      containers:
      - image: vineethac/fastapi-llm-app:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - python3
            - liveness.py
          failureThreshold: 3
          initialDelaySeconds: 600
          periodSeconds: 180
          successThreshold: 1
          timeoutSeconds: 300
        name: fastapi-llm-app
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 600
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 60
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi-llm-app
  name: fastapi-llm-app
  namespace: default
spec:
  ports:
  - nodePort: 30590
    port: 5000
  selector:
    app: fastapi-llm-app
  type: LoadBalancer

      